#!/bin/bash
# Checks autoscaling dates to ensure load configuration group is up to date

asgname=$1
logger sensu-check 

lcname=$(
	aws autoscaling describe-auto-scaling-groups \
		--auto-scaling-group-name $asgname \
		--output json \
	| awk \
			-F: '/LaunchConfiguration/ { print gensub(/\"(.*)\",/, "\\1", "g", $2) }' \
	| awk '{ $1=$1; print }'
)


imageid=$(
  aws autoscaling describe-launch-configurations \
    --launch-configuration-names $lcname \
    --output json \
  | awk \
      -F: '/ImageId/ { print gensub(/\"(ami-.*)\",/, "\\1", "g", $2); exit }' \
  | awk '{ $1=$1; print }'
)

now=`date +%s`
then=%(
  date -d `
    aws ec2 describe-images \
      --image-ids $imageid \
    | awk '/CreationDate/ { print gensub(/\"([0-9].*)\",/, "\\1", "g", $2) }'
  ` +%s
)

# short circuit if date failed, otherwise check if difference is greater than
# a day
if [[ $? != 0 ]]; then
  echo "failed to determine ami date"
  exit 2
fi

elif [[ `expr $now - $then` > 86400 ]]; then
  echo "ami is older than a day"
  exit 2
fi

echo OK!
exit 0
