#!/bin/bash
# Checks autoscaling dates to ensure load configuration group is up to date

asgname=$1
logger "sensu-check asg=$asgname msg=start" 

lcname=$(
	aws autoscaling describe-auto-scaling-groups \
		--auto-scaling-group-name $asgname \
		--output json \
	| awk \
			-F: '/LaunchConfiguration/ { print gensub(/\"(.*)\",/, "\\1", "g", $2) }' \
	| awk '{ $1=$1; print }'
)
logger "sensu-check asg=$asgname lc=$lcname msg=describe load configuration"


imageid=$(
  aws autoscaling describe-launch-configurations \
    --launch-configuration-names $lcname \
    --output json \
  | awk \
      -F: '/ImageId/ { print gensub(/\"(ami-.*)\",/, "\\1", "g", $2); exit }' \
  | awk '{ $1=$1; print }'
)
logger "sensu-check asg=$asgname lc=$lcname image=$imageid msg=describe image"

now=`date +%s`
creationdate=$(
  aws ec2 describe-images \
      --image-ids $imageid \
    | awk '/CreationDate/ { print gensub(/\"([0-9].*)\",/, "\\1", "g", $2) }'
)
logger "sensu-check asg=$asgname lc=$lcname image=$imageid date=$creationdate" \
       "msg=get image creation date"
then=$(
  date -d $creationdate +'%s'
)
difference=$(( $now - $then ))

# short circuit if date failed, otherwise check if difference is greater than
# a day
if [[ $? != 0 ]]; then
  logger "sensu-check asg=$asgname lc=$lcname image=$imageid date=$creationdate" \
         "msg=date failed"
  echo "failed to determine ami date"
  exit 2

elif [ $difference -gt 86400 ]; then
  logger "sensu-check asg=$asgname lc=$lcname image=$imageid date=$creationdate" \
         "difference=`expr $now - $then`" \
         "msg=ami older than a day"
  echo "ami is older than a day"
  exit 2

else
  logger "sensu-check asg=$asgname lc=$lcname image=$imageid date=$creationdate" \
         "difference=`expr $now - $then`" \
         "msg=success"
  echo OK
  exit 0
fi

